name: Test Lighthouse Check
on: [pull_request,workflow_dispatch]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'http://localhost/'
